// 2022/11/11 22:30

/*
	PERKALIAN ATAU PEMBAGIAN AKAN DI LAKUKAN TERLEBIH DAHULU 
	JIKA DI LAKUKAN PERKALIAN DAN PEMBAGIAN MAKA OPERASI YANG DI LAKUKAN TERLEBIH DAHULU DARI KIRI KE KANAN 
	TANDA KURUNG MAKA AKAN MEMBUAT OPERASI DI LAKUKAN TERLEBIH DAHULU 
*/
public class Main {
	public static void main (String[] args){
		int hasil = 5*(2+10);
		System.out.print(hasil);
	}
}